# Taller 4

In [1]:
import math
import time
import matplotlib.pyplot as plt
from itertools import chain
import random as rnd
import numpy as np
import pylab as pl
import time as tm
%matplotlib inline

## Punto 1

Implemente un método que retorne la subsecuencia común más larga (SCL) apartir de la matriz C construida por el algoritmo de PD que calcula la longitud de la SCL.

In [2]:


global C

def lcs(X,Y):
    global C
    C = np.ones((len(X)+1,len(Y)+1))*-1
    lcs3(X,Y,len(X),len(Y))
    return C[len(X),len(Y)], C
    

def lcs3(x,y,i,j):
    global C
    if C[i,j] == -1:
        if i == 0 or j == 0:
            C[i,j] = 0
        else:
            if x[i-1]==y[j-1]:
                C[i,j] = lcs3(x,y,i-1,j-1)+1
            else:
                C[i,j] = max(lcs3(x,y,i-1,j),lcs3(x,y,i,j-1))
                
    return C[i,j]

In [3]:

def subCom(matrix,A,B):
    n = len(matrix) - 1
    m = len(matrix[0]) - 1
    subsecuencia = ""
    while (m > 0 and m > 0):
        if(matrix[n][m - 1] == matrix[n][m]):
            
            m = m - 1
            
        if(matrix[n][m] == matrix[n-1][m]):
            
            n = n - 1
            
        if(matrix[n][m] == matrix[n - 1][m - 1] + 1):
            subsecuencia = A[n-1] + subsecuencia;
                
            n = n - 1
            m = m - 1
            
    return subsecuencia

In [4]:
A = 'iiopoi'
B = 'iiiiii'
subsecuencia, mat = lcs(A,B)
print mat
print subCom(mat,A,B)

[[ 0.  0.  0.  0. -1. -1. -1.]
 [ 0.  1.  1.  1.  1. -1. -1.]
 [-1.  1.  2.  2.  2.  2. -1.]
 [ 0.  1.  2.  2.  2.  2. -1.]
 [ 0.  1.  2.  2.  2.  2. -1.]
 [ 0.  1.  2.  2.  2.  2. -1.]
 [-1. -1. -1. -1. -1. -1.  3.]]
iii


## Punto 2

### 1. Implemente un método para determinar los cortes que se deben realizar a partir de la solución de PD que encuentra el valor de la solución óptima.

In [9]:

def cortes(vector,num):
    n = len(vector) + 1
    m = num + 1;
    matrix = np.zeros((n,m))
    
    solucion = []
    for i in range(num,m):
        matrix[1][i] = i * vector[0]
        
    for i in range(2,n):
        for j in range(1,m):
            
            if (j < i):
                matrix[i][j] = matrix[i-1][j]
            else:
                matrix[i][j] = max(matrix[i-1][j], matrix[i][j - i] + vector[i - 1])
    x = n - 1
    y = m - 1 
    
    while (x > 0 and y > 0):
        
        if (matrix[x][y] == matrix[x - 1][y]):
            
            x = x - 1
        elif(matrix[x][y] == matrix[x][y - i] + vector[x - 1]):
            
            solucion.append(x)
            y = y - x 
    
    return  solucion, matrix[n-1][m-1] 


In [ ]:
a = [2,5,7,8]
n = 5

print cortes(a,n)

## Punto 3

In [6]:
def distancia(str1,str2):
    
    n=len(str1)

    m=len(str2)

    matrix = np.zeros((n+1,m+1))

    for i in range(0,n+1): 

        matrix[i][0] = i
    for j in range(0,m+1):

        matrix[0][j] = j
    for i in range (1,n+1):

        for j in range(1,m+1):

            if str1[i-1] == str2[j-1]:
                matrix[i][j] = matrix[i-1][j-1] 

            else :
                matrix[i][j]= min(matrix[i][j-1],matrix[i-1][j],matrix[i-1][j-1])+1

    return matrix[i][j]

In [7]:
w1 = "hola"
w2 = "hole"

print distancia(w1,w2)

1.0
